
TESTING_MYSQL_HOST = "10.0.0.0"
TESTING_MYSQL_PORT = "5001"
TESTING_MYSQL_USER = "user"
TESTING_MYSQL_PWD = "xxxxxxxxxxx"

TESTING_MYSQL_NAME="co_TESTING"
TESTING_MYSQL_CHARSET="utf8"
TESTING_MYSQL_PREFIX="TESTING_"



